/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebanking;

/**
 *
 * @author Omanshu Mahawar
 */
public class employeemenu extends javax.swing.JFrame {

    /**
     * Creates new form employeemenu
     */
    public employeemenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addaccount = new javax.swing.JButton();
        cusacdetails = new javax.swing.JButton();
        deleteacc = new javax.swing.JButton();
        depmoney = new javax.swing.JButton();
        newemployee = new javax.swing.JButton();
        newemployee1 = new javax.swing.JButton();
        newemployee2 = new javax.swing.JButton();
        newemployee3 = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Pictures\\netbeans\\logo2.PNG")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Employee Main Menu");

        addaccount.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        addaccount.setText("Add Account");
        addaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccountActionPerformed(evt);
            }
        });

        cusacdetails.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        cusacdetails.setText("Customer A/c Details");
        cusacdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusacdetailsActionPerformed(evt);
            }
        });

        deleteacc.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        deleteacc.setText("Delete Account");
        deleteacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteaccActionPerformed(evt);
            }
        });

        depmoney.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        depmoney.setText("Deposit Money");
        depmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depmoneyActionPerformed(evt);
            }
        });

        newemployee.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        newemployee.setText("Add New Employee");
        newemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newemployeeActionPerformed(evt);
            }
        });

        newemployee1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        newemployee1.setText("Fixed Deposit");
        newemployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newemployee1ActionPerformed(evt);
            }
        });

        newemployee2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        newemployee2.setText("Delete Employee");
        newemployee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newemployee2ActionPerformed(evt);
            }
        });

        newemployee3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        newemployee3.setText("Loan");
        newemployee3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newemployee3ActionPerformed(evt);
            }
        });

        EXIT.setBackground(new java.awt.Color(255, 0, 51));
        EXIT.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newemployee2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newemployee3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteacc, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(depmoney, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(cusacdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newemployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EXIT)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addaccount)
                    .addComponent(cusacdetails))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteacc)
                    .addComponent(depmoney))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newemployee)
                    .addComponent(newemployee1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newemployee2)
                    .addComponent(newemployee3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(EXIT)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccountActionPerformed
        addnewaccount info = new addnewaccount();
        info.setVisible(true);

        dispose();
    }//GEN-LAST:event_addaccountActionPerformed

    private void cusacdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusacdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusacdetailsActionPerformed

    private void deleteaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteaccActionPerformed
        // TODO add your handling code here:
        deleteaccount info = new deleteaccount();
        info.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_deleteaccActionPerformed

    private void depmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depmoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depmoneyActionPerformed

    private void newemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newemployeeActionPerformed
        // TODO add your handling code here:
        jaddnewemployee info = new jaddnewemployee();
        info.setVisible(true);
        dispose();
    }//GEN-LAST:event_newemployeeActionPerformed

    private void newemployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newemployee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newemployee1ActionPerformed

    private void newemployee2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newemployee2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newemployee2ActionPerformed

    private void newemployee3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newemployee3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newemployee3ActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeemenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeemenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton addaccount;
    private javax.swing.JButton cusacdetails;
    private javax.swing.JButton deleteacc;
    private javax.swing.JButton depmoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newemployee;
    private javax.swing.JButton newemployee1;
    private javax.swing.JButton newemployee2;
    private javax.swing.JButton newemployee3;
    // End of variables declaration//GEN-END:variables
}
