/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebanking;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Omanshu Mahawar
 */
public class employeelogin extends javax.swing.JFrame {

    /**
     * Creates new form employeelogin
     */
    public employeelogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtempcode = new javax.swing.JTextField();
        EXIT = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtempname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebanking/Webp.net-resizeimage (2).jpg"))); // NOI18N
        jLabel6.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jpassword.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpassword);
        jpassword.setBounds(450, 520, 294, 42);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(749, 208, 0, 170);

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Employee Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 230, 381, 57);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 520, 171, 43);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setText("Employee Code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 370, 281, 43);

        jtxtempcode.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(jtxtempcode);
        jtxtempcode.setBounds(450, 370, 294, 42);

        EXIT.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT);
        EXIT.setBounds(399, 626, 76, 49);

        LogIn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        LogIn.setText("LOG IN");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        getContentPane().add(LogIn);
        LogIn.setBounds(140, 626, 106, 49);

        Back.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(660, 620, 87, 49);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("Employee name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 450, 291, 43);

        jtxtempname.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(jtxtempname);
        jtxtempname.setBounds(450, 450, 294, 42);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebanking/Webp.net-resizeimage (2).jpg"))); // NOI18N
        jLabel7.setText("jLabel5");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 20, 725, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed

        int f = 0;
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/omibbank","root","");
            Statement stmt = con.createStatement();
            int emcode = Integer.parseInt(jtxtempcode.getText());
            String emname = jtxtempname.getText();
            String password = jpassword.getText();
            String query = "select * from newemployee;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                int ec = rs.getInt("emplyeecode");
                String em = rs.getString("name");
                String p = rs.getString("password");

                if(ec==emcode && em.equals(emname) && p.equals(password))
                {
                    f = f+1;
                }
            }
            if(f!=0)
            {
                employeemenu info = new employeemenu();
                info.setVisible(true);

                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
                jtxtempcode.setText(null);
                jpassword.setText(null);
                jtxtempname.setText(null);
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_LogInActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        selecttype info = new selecttype();
        info.setVisible(true);

        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtxtempcode;
    private javax.swing.JTextField jtxtempname;
    // End of variables declaration//GEN-END:variables
}
